version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - REPOSITORY_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - BRANCH=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | awk -F '/' '{print $3}')
      - PULL_BRANCH=$BRANCH
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker pull $REPOSITORY_URL:$BRANCH || (docker pull $REPOSITORY_URL:master && PULL_BRANCH=master) || true

  build:
    commands:
      - echo Build started on `date`
      - docker build --cache-from $REPOSITORY_URL:$PULL_BRANCH --build-arg AWS_ACCOUNT=$AWS_ACCOUNT_ID --build-arg NPM_TOKEN=$NPM_TOKEN -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $REPOSITORY_URL:$BRANCH

  post_build:
    commands:
      - echo Build completed `date`
      - echo Pushing image
      - docker push $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URL:$BRANCH
